In [1]:
!pip install mlxtend pandas

Requirement already satisfied: mlxtend in .\AppData\Roaming\Python\Python314\site-packages (0.25.0)
Requirement already satisfied: pandas in .\AppData\Roaming\Python\Python314\site-packages (3.0.5)
Requirement already satisfied: scipy>=1.16.3 in .\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.18.0)
Requirement already satisfied: numpy>=2.3.5 in .\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (2.5.2)
Requirement already satisfied: scikit-learn>=1.8.0 in .\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.9.0)
Requirement already satisfied: matplotlib>=3.10.8 in .\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in .\AppData\Roaming\Python\Python314\site-packages (from mlxtend) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (26.3)
Requirement already satisfied: pillow>=9 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.10.8->mlxtend) (3.3.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Roaming\Python\Python314\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
dataset = [
    ['MILK', 'BREAD', 'BISCUIT'],
    ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
    ['BREAD', 'CORNFLAKES'],
    ['BREAD', 'JAM'],
    ['MAGGI', 'BREAD', 'BISCUIT'],
    ['MAGGI', 'TEA'],
    ['MAGGI', 'COFFEE'],
    ['MAGGI', 'TEA', 'COFFEE'],
    ['SUGAR', 'COFFEE'],
    ['SUGAR', 'TEA']
]

In [4]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

print("One-Hot Encoded Dataset Shape:", df.shape)
df.head()

One-Hot Encoded Dataset Shape: (10, 9)

   BISCUIT  BREAD  COFFEE  CORNFLAKES    JAM  MAGGI   MILK  SUGAR    TEA
0     True   True   False       False  False  False   True  False  False
1     True   True   False        True  False  False   True  False  False
2    False   True   False        True  False  False  False  False  False
3    False   True   False       False   True  False  False  False  False
4     True   True   False       False  False   True  False  False  False

In [5]:
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)
frequent_itemsets.sort_values(['support'], ascending=False, inplace=True)

print("Frequent Itemsets:")
frequent_itemsets

Frequent Itemsets:

    support                           itemsets
1       0.5                 frozenset({BREAD})
4       0.4                 frozenset({MAGGI})
0       0.3               frozenset({BISCUIT})
2       0.3                frozenset({COFFEE})
7       0.3                   frozenset({TEA})
8       0.3        frozenset({BREAD, BISCUIT})
3       0.2            frozenset({CORNFLAKES})
6       0.2                 frozenset({SUGAR})
5       0.2                  frozenset({MILK})
9       0.2         frozenset({MILK, BISCUIT})
10      0.2     frozenset({CORNFLAKES, BREAD})
11      0.2           frozenset({MILK, BREAD})
12      0.2         frozenset({MAGGI, COFFEE})
13      0.2            frozenset({TEA, MAGGI})
14      0.2  frozenset({MILK, BREAD, BISCUIT})

In [6]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.sort_values(['lift'], ascending=False, inplace=True)

print("Association Rules:")
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

Association Rules:

,antecedents,consequents,support,confidence,lift
3,frozenset({BISCUIT}),frozenset({MILK}),0.2,0.666667,3.333333
2,frozenset({MILK}),frozenset({BISCUIT}),0.2,1.000000,3.333333
17,frozenset({BISCUIT}),"frozenset({MILK, BREAD})",0.2,0.666667,3.333333
16,frozenset({MILK}),"frozenset({BREAD, BISCUIT})",0.2,1.000000,3.333333
12,"frozenset({MILK, BREAD})",frozenset({BISCUIT}),0.2,1.000000,3.333333
13,"frozenset({BREAD, BISCUIT})",frozenset({MILK}),0.2,0.666667,3.333333
1,frozenset({BISCUIT}),frozenset({BREAD}),0.3,1.000000,2.000000
0,frozenset({BREAD}),frozenset({BISCUIT}),0.3,0.600000,2.000000
4,frozenset({BREAD}),frozenset({CORNFLAKES}),0.2,0.400000,2.000000
5,frozenset({CORNFLAKES}),frozenset({BREAD}),0.2,1.000000,2.000000
15,frozenset({BREAD}),"frozenset({MILK, BISCUIT})",0.2,0.400000,2.000000
14,"frozenset({MILK, BISCUIT})",frozenset({BREAD}),0.2,1.000000,2.000000
7,frozenset({MILK}),frozenset({BREAD}),0.2,1.000000,2.000000
6,frozenset({BREAD}),frozenset({MILK}),0.2,0.400000,2.000000
9,frozenset({COFFEE}),frozenset({MAGGI}),0.2,0.666667,1.666667
8,frozenset({MAGGI}),frozenset({COFFEE}),0.2,0.500000,1.666667
10,frozenset({TEA}),frozenset({MAGGI}),0.2,0.666667,1.666667
11,frozenset({MAGGI}),frozenset({TEA}),0.2,0.500000,1.666667